language: generic
sudo: required
services:
  - docker

language: python

before_install:
  - echo before_install
  - docker build -t hamaro/docker-react-travis -f Dockerfile.dev .
  - sed -i 's/DECRYPT_COMMAND/openssl aes-256-cbc -K $encrypted_4d38fdbd1b17_key -iv $encrypted_4d38fdbd1b17_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d/g' .travis.yml
  - sed -i 's/docker-react-travis/${DEVSHELL_PROJECT_ID}/g' .travis.yml

script:
  - echo script
  - docker run -e CI=true hamaro/docker-react-travis npm run test

deploy:
  provider: gae
  project: docker-react-travis
  keyfile: client-secret.json
  verbosity: debug
  on: master
