language: generic
sudo: required
services:
  - docker

language: python

before_install:
  - echo before_install
  - docker build -t hamaro/docker-react-travis -f Dockerfile.dev .


script:
  - echo script
  - docker run -e CI=true hamaro/docker-react-travis npm run test

deploy:
  provider: gae
  project: docker-react-travis
  keyfile: client-secret.json
  verbosity: debug
  on: master
